name: Main
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

permissions:
  actions: write
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: imagick, swoole
          tools: composer:2.7
          coverage: pcov

      - name: Install dependencies
        uses: ramsey/composer-install@v2

      - name: Setup env
        run: |
            cp .env.example .env
            php artisan key:generate

      - name: Run tests
        run: vendor/bin/phpunit

      - uses: qltysh/qlty-action/coverage@main
        with:
          oidc: true
          files: coverage/clover.xml
